"""add payments table

Revision ID: 99d1b9fa577f
Revises: 001ed74f409c
Create Date: 2026-05-06 20:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d1b9fa577f'
down_revision: Union[str, Sequence[str], None] = '001ed74f409c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('plan_type', sa.String(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.String(), nullable=False),
        sa.Column('payment_method', sa.Enum('MTN_UGANDA', 'AIRTEL_UGANDA', 'CARD', name='paymentmethod'), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus'), nullable=False),
        sa.Column('transaction_ref', sa.String(), nullable=True),
        sa.Column('checkout_request_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('checkout_request_id'),
        sa.UniqueConstraint('transaction_ref')
    )
    # op.add_column('users', sa.Column('last_transaction_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_transaction_at')
    op.drop_table('payments')
    # ### end Alembic commands ###
