"""add plan type and usage tracking to user

Revision ID: e19b0bbe63ca
Revises: 10601b00d6d3
Create Date: 2026-05-06 20:47:22.666992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19b0bbe63ca'
down_revision: Union[str, Sequence[str], None] = '10601b00d6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_type', sa.Enum('FREE', 'PAID', name='plantype'), nullable=False, server_default='FREE'))
    op.add_column('users', sa.Column('transactions_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('payment_expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_expiry_date')
    op.drop_column('users', 'transactions_this_month')
    op.drop_column('users', 'plan_type')
    # ### end Alembic commands ###
